### PR TITLE
Fix reraise usage

### PR DESCRIPTION
**Pull request by agchitu**
six.reraise expects an instance of the exception as second argument, carolina provides a string with the message as value not the instance.
Create an instance of the error with the given type and the given message

### CODE REVIEW

**Comment by andreabrambilla** [comment]
I did try the "old" version with Python 2.7 and it works fine. Did the behavior change in Python 3?
Please just make sure your changes work with both Python 2 and Python 3
A simple test can be to run IEverest with any config file (eg, any of the `math_func`), start the optimization then stop it. If things work correctly you should see `Exception: Optimization stopped` 

I don't have time to test this now, if you want we can have a chat tomorrow morning

**Comment by agchitu** [comment]
Thanks Andrea. I am not sure where the difference is coming from. 
I'll check what is the behavior in Python 2. In Python3 the value is set to the string and not the instance...

**Comment by andreabrambilla** [comment]
I have checked the code once more, maybe the confusion comes from the fact that in the C++ code, those properties are set using `int PyObject_SetAttrString(PyObject *o, const char *attr_name, PyObject *v)` (https://docs.python.org/3.7/c-api/object.html#c.PyObject_SetAttrString). 

I think the `String` part refers to the fact that the python attribute is referred to with a `const char*`, but the value is expected to be a `PyObject`. 
And all the values passed to those calls are retrieved by `PyErr_Fetch`, so I would expect them to be already of the correct type.

Both `PyErr_Fetch` and `PyObject_SetAttrString` seems to be the same in Python 2 and 3, so I wouldn't expect a different behavior. I would be prone to close this PR without merging, but let me know if you run some tests and things work differently than expected

**Comment by agchitu** [comment]
I'm working on it today/now.... the behavior is different in Python3 that's how I found out there needs to be adjusted. I'm going to do some more tests and let you know their output

**Comment by agchitu** [comment]
In Python3 without the changes from this PR in case of an exception this is what we get: 
```
<class 'NameError'>
name 'range1' is not defined
<class 'str'>
Traceback (most recent call last):
  File "/home/chituag/build_everest_py3/everest_bin/bin/everest", line 11, in <module>
    load_entry_point('everest==0.5rc2.dev20+g9c6b38e', 'console_scripts', 'everest')()
  File "/home/chituag/build_everest_py3/everest_bin/lib/python3.7/site-packages/everest-0.5rc2.dev20+g9c6b38e-py3.7.egg/everest/suite.py", line 216, in everest_entry
    display_all_jobs=options.verbose)
  File "/home/chituag/build_everest_py3/everest_bin/lib/python3.7/site-packages/everest-0.5rc2.dev20+g9c6b38e-py3.7.egg/everest/suite.py", line 598, in start_optimization
    return workflow.start_optimization()
  File "/home/chituag/build_everest_py3/everest_bin/lib/python3.7/site-packages/everest-0.5rc2.dev20+g9c6b38e-py3.7.egg/everest/suite.py", line 567, in start_optimization
    callback=self._optimization_callback
  File "/home/chituag/build_everest_py3/everest_bin/lib/python3.7/site-packages/Seba-2.5a2.dev6+gdcb6f7a.d20190117-py3.7.egg/seba/optim/workflow/enopt_workflow.py", line 447, in start_optimization
  File "/home/chituag/build_everest_py3/everest_bin/lib/python3.7/site-packages/carolina-1.0-py3.7-linux-x86_64.egg/dakota.py", line 90, in run_dakota
    run_dakota(infile, stdout, stderr, restart=restart, throw_on_error=throw_on_error)
  File "/home/chituag/build_everest_py3/everest_bin/lib/python3.7/site-packages/carolina-1.0-py3.7-linux-x86_64.egg/dakota.py", line 235, in run_dakota
    reraise(exc.type, exc.value, exc.traceback)
  File "/home/chituag/build_everest_py3/everest_bin/lib/python3.7/dist-packages/six.py", line 691, in reraise
    if value.__traceback__ is not tb:
AttributeError: 'str' object has no attribute '__traceback__'
```
There is an issue with the value...
In Python2 with a similar error the code works as expected indeed but the error and traceback looks like this:
```
<type 'exceptions.NameError'>
global name 'xrange1' is not defined
<type 'str'>
Traceback (most recent call last):
  File "/home/tom/install/bin/everest", line 11, in <module>
    load_entry_point('everest==0.5rc2.dev21+g6a7b727', 'console_scripts', 'everest')()
  File "/home/tom/install/lib/python2.7/site-packages/everest-0.5rc2.dev21+g6a7b727-py2.7.egg/everest/suite.py", line 217, in everest_entry
    display_all_jobs=options.verbose)
  File "/home/tom/install/lib/python2.7/site-packages/everest-0.5rc2.dev21+g6a7b727-py2.7.egg/everest/suite.py", line 599, in start_optimization
    return workflow.start_optimization()
  File "/home/tom/install/lib/python2.7/site-packages/everest-0.5rc2.dev21+g6a7b727-py2.7.egg/everest/suite.py", line 567, in start_optimization
    callback=self._optimization_callback
  File "build/bdist.linux-x86_64/egg/seba/optim/workflow/enopt_workflow.py", line 445, in start_optimization
  File "/home/tom/install/lib/python2.7/site-packages/carolina-1.0-py2.7-linux-x86_64.egg/dakota.py", line 90, in run_dakota
    run_dakota(infile, stdout, stderr, restart=restart, throw_on_error=throw_on_error)
  File "/home/tom/install/lib/python2.7/site-packages/carolina-1.0-py2.7-linux-x86_64.egg/dakota.py", line 233, in run_dakota
    reraise(exc.type, exc.value, exc.traceback)
  File "/home/tom/install/lib/python2.7/site-packages/carolina-1.0-py2.7-linux-x86_64.egg/dakota.py", line 295, in dakota_callback
    return driver.dakota_callback(**kwargs)
  File "build/bdist.linux-x86_64/egg/seba/dakota/dakota_driver.py", line 146, in dakota_callback
  File "build/bdist.linux-x86_64/egg/seba/dakota/compute_response.py", line 87, in computeRequestResponse
  File "build/bdist.linux-x86_64/egg/seba/dakota/compute_response.py", line 101, in _compute_response
  File "build/bdist.linux-x86_64/egg/seba/optim/workflow/enopt_workflow.py", line 2306, in prepare_to_compute_results
  File "build/bdist.linux-x86_64/egg/seba/optim/workflow/enopt_workflow.py", line 1075, in createControlSet
NameError: global name 'xrange1' is not defined
```
Note that in both cases the type (third line in both examples) of the exc.value is ```str```

**Comment by agchitu** [comment]
The difference comes from six.py in the way the ```reraise``` is implemented:
```python
if PY3:
    exec_ = getattr(moves.builtins, "exec")

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
                raise value.with_traceback(tb)
            raise value
        finally:
            value = None
            tb = None

else:
    def exec_(_code_, _globs_=None, _locs_=None):
        """Execute code in a namespace."""
        if _globs_ is None:
            frame = sys._getframe(1)
            _globs_ = frame.f_globals
            if _locs_ is None:
                _locs_ = frame.f_locals
            del frame
        elif _locs_ is None:
            _locs_ = _globs_
        exec("""exec _code_ in _globs_, _locs_""")

    exec_("""def reraise(tp, value, tb=None):
    try:
        raise tp, value, tb
    finally:
        tb = None
""")
```
I'll change the code to include both Py2 and Py3.

**Comment by agchitu** [comment]
@andreabrambilla Done. This is now working in both Python2 and Python3. Also included an exception test. Please have a look at this.

**Review by andreabrambilla — APPROVED** [review]
Nice job :+1:

**Pull request merged**
