### PR TITLE
Update to include python 3.11

### PR DESCRIPTION
**Pull request by andreas-el**
Resolves https://github.com/equinor/scout/issues/935

### CODE REVIEW

**Review by yngve-sk — APPROVED** [review]
LGTM with tests passing, consider py3.12

**Comment by andreas-el** [comment]
> LGTM with tests passing, consider py3.12

Indeed. Already working on it. 👍

**Comment by oysteoh** [comment]
Maybe in the matrix build consider also removing some versions? Could we i.e test lower and upper version ( 3.8 and 3.11 / 3.12 )? Or do we see it necessary to test all?

**Comment by andreas-el** [comment]
> Maybe in the matrix build consider also removing some versions? Could we i.e test lower and upper version ( 3.8 and 3.11 / 3.12 )? Or do we see it necessary to test all?

I agree we could stop doing at least 3.9 and 3.10 for the time being.
I do want to keep them there until I get 3.12 running though, just to see I don't break anything.

**Pull request merged**
