### PR TITLE
[WIP] Update to python 3

### PR DESCRIPTION
**Pull request by elenahechen**
solves Statoil/everest#363

### CODE REVIEW

**Comment by joakim-hove** [comment]
I am not familiar with the details of this, but to me it seems weird to focus on Python 3.4 instead of 3.6.

**Comment by pgdr** [comment]
I agree that _we_ will probably use Python 3.6, I think that the lower the better, and would actually propose compiling it against Python 3.3!  The reason is that since Python 3.4, 3.5, 3.6, and soon 3.7 are all backwards compatible, the lowest version we can build with, the more versions we can support.

In addition, Python 3.3 (or is it 3.5?) is the one that ships with RHEL SCL which we might have to support, but not in the near future.

However, I believe this is just an exercise from Elena's perspective.  If we _manage_ to get it to compile with Python 3.4, I _ass/u/me_ we will be able to compile it with 3.x for any x in [2,7].

**Comment by elenahechen** [comment]
My motivation here is libboost-python in my machine (ubuntu trusty) only reaches till version 1.54 and compiles to python 2.x and 3.4. In the latest version of ubuntu, libboost is supported til 1.6x

So far I haven't found the way to use by default the 3.4 version when linking. Travis is using `/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0` when `/usr/lib/x86_64-linux-gnu/libboost_python-py34.so.1.54.0` also exists in the same directory (at least on mine it does)

I've been browsing around and haven't found the solution yet.

**Comment by jokva** [comment]
> In addition, Python 3.3 (or is it 3.5?) is the one that ships with RHEL SCL which we might have to support, but not in the near future.

3.5

**Comment by andreabrambilla** [comment]
superseded by #20

**Pull request closed without merging**
