### PR TITLE
Add Travis parallel builds for Python2 and Python3

### PR DESCRIPTION
**Pull request by agchitu**
Try parallel Python2.7 and Python3.7 builds

### CODE REVIEW

**Comment by markusdregi** [comment]
I think the goal should be to be compatible with at least _2.7_, _3.6_ and _3.7_. But first things first of course ;)

**Comment by agchitu** [comment]
@markusdregi @jokva dakota does not seem to be built with Python 3 support on the ppa
This is the log from the last build on https://launchpad.net/~jokva/+archive/ubuntu/carolina : 
https://launchpadlibrarian.net/401377287/buildlog_ubuntu-trusty-i386.dakota_6.6-0ubuntu9~trusty1_BUILDING.txt.gz

In order to build with Python 3 support the cmake call should be something like: 
```cmake
CMAKE_PREFIX/bin/cmake \
-DPYTHON_LIBRARY=$PYTHON_LIB \
-DPYTHON_INCLUDE_DIRS=$PYTHON_INCLUDE_DIR \
-DPYTHON_NUMARRAY_INCLUDE_DIR="$NUMARRAY_INCLUDE_DIR" \
-DCMAKE_INSTALL_PREFIX=$DAKOTA_PREFIX \
-DBOOST_ROOT=$BOOST_PREFIX \
-DBOOST_INCLUDEDIR=$BOOST_PREFIX/include/ \
-DBUILD_SHARED_LIBS=ON \
-DDAKOTA_PYTHON=ON \
-DDAKOTA_PYTHON_NUMPY=ON \
-DDAKOTA_DLL_API=OFF \
-DHAVE_X_GRAPHICS=OFF \
-DDAKOTA_ENABLE_TPL_TESTS=OFF \
-DCMAKE_CXX_FLAGS="-fpermissive" \
-DCMAKE_CXX_STANDARD=11 \
-DCMAKE_CXX_STANDARD_REQUIRED=ON \
../. && \ 
```

Travis is failing on my PR, see the error there as well. I am using trusty which comes with boost_1.54, python 2.7 and python 3.4

**Comment by agchitu** [comment]
Carolina builds with Python 2.7, 3.4, 3.5, 3.6 and 3.7.
Travis does not support bionic, zesty nor cosmic, the tests for 3.5, 3,6 and 3.7 are done on xenial.

**Comment by agchitu** [comment]
I merge this now! I guess there is not much to review....

**Pull request merged**
