### PR TITLE
Nompi build carolina - get even with the upstream master in properties..

### PR DESCRIPTION
**Pull request by agchitu**
I am trying to get a stable place after removing the develop branch. Some of the commits below have been already merged into the master....

### CODE REVIEW

**Comment by joakim-hove** [comment]
> Some of the commits below have been already merged into the master....

Ehh yes - you could say that; looking at `Files changed` the only net change is one single line white-space. I suggest this is closed?

**Comment by agchitu** [comment]
How do I avoid this one here? I just want my branch to say even with master.

**Comment by joakim-hove** [comment]
> I just want my branch to say even with master.

Well - if you just want your personal `master` up to date with `upstream/master`:
```bash
cmd> git fetch upstream
cmd> git checkout master
cmd> git reset --hard upstream/master
```

My usual workflow when starting on a new feature is:

**1: Make sure `master`is current**
```
cmd> git fetch upstream
cmd> git checkout master
cmd> git merge upstream/master
```

**2: Start a feature branch::
```
cmd> git checkout -b new-feature
[ Develop new features ... ]
cmd> git commit ...
```

**3: Incorporate new changes in upstream**
```
cmd> git fetch upstream
cmd> git checkout new-feature
cmd> git rebase upstream/master
```

**4: Push changes**
```
cmd> git push -u origin new_feature
```

If it takes long time before `new_feature` is merged you might want to repeat 3) and subsequently force push with: `git push -f origin new_feature`.

**Comment by agchitu** [comment]
Thanks, I do the same as well. This time it does not work like that anymore... this is due to the develop/master stuff.

**Pull request closed without merging**
